### PR TITLE
adds support for getInnerHTML (declarative shadow DOM)

### PR DESCRIPTION
**Pull request by ttraenkler**
Adds support for `getInnerHTML` fixing https://github.com/WebReflection/linkedom/issues/210.

@WebReflection: Since this is my first larger contribution, I would appreciate early feedback  if you need anything to be changed. I have tried to adopt the coding style used in the project and added minimal unit tests.

As we [discussed](https://github.com/WebReflection/linkedom/issues/178#issuecomment-1605403957) for this first implementation I decided to adapt an [existing polyfill](https://gist.github.com/developit/54f3e3d1ce9ed0e5a171044edcd0784f) from @developit. 

It uses innerHTML to serialize the shadow root which could optimized away, but might require more complete support for shadow DOM so I am hesitant to do this now before shadow DOM is properly supported in linkedom. The polyfill already improves on the current state of no support for _declarative_ shadow DOM enough that I would suggest to leave optimization to a separate issue as it might require work on broader support for shadow DOM and would block this issue until that has landed. 

This way we can start broader testing earlier in the spirit of [make it work, make it right, make it fast](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast) and we can identify which shadow DOM features are missing or need to be fixed (like #178 which I have stumbled upon and fixed along the way). 

As I found in the comments I made ShadowRoot inherit from DocumentFragment.

### CODE REVIEW

**Comment by WebReflection** [comment]
Thanks @ttraenkler, I'll try to have a look ASAP but I won't likely do that until coverage is back to 100%. If there is some path *really* hard to reason about (for coverage/edge cases) then feel free to add a c8 comment to ignore that step with some explanation about *why* too, thanks!

**Comment by ttraenkler** [comment]
@WebReflection Yes, I just noticed and fixed this.

**Comment by WebReflection** [comment]
This MR is still in a **draft** state and it has merge conflicts ... please make it review ready after rebasing from main, thanks!

**Comment by ttraenkler** [comment]
As discussed I clarified with the champion of the getInnerHTML proposal that this is not yet standardized and likely never will due to lack of consensus. Therefore closing. Thanks anyways for considering!

**Pull request closed without merging**
