### PR TITLE
Feat: types

### PR DESCRIPTION
**Pull request by qwelias**
An attempt at fixing types.
There's a weird TS issue of `Declaration emit for this file requires using private name 'name' from module 'file'. An explicit type annotation may unblock declaration emit.` kind, that I'm not sure how to tackle rn.

Maybe someone would have a better idea.

Also `SVGDocument` is not defined on `globalThis` or anywhere.

### CODE REVIEW

**Comment by WebReflection** [comment]
Holy shit this is **huge** 🤯

Thank you so much for this effort, as I know TS users will love this, even if I don't TS myself.

One thing though, I'd love to be a squashed single commit, so it's easier to review/check/revert, etc ... I hope that's not a big issue (ask me more if it is, squashing is relatively easy).

I also would like to know when/who/how this is a *WIP*, and why it wouldn't be a *WIP* anymore at some point ... as everything looks good to me, mind expanding on why this couldn't be *not* a *WIP*?

the thing about *WIP* is that coverage and builds don't run, but for what I can see/tell nothing in here should bother tests.

Thanks again for this, I love it in general, willing to move it forward ASAP 🥳

**Comment by WebReflection** [comment]
@qwelias any answer to my comment?

**Comment by qwelias** [comment]
This is huge thanks to JSDoc that was already in place thanks to your work :)

Sure I'll squash it np.

DoD: `tsc -p .` compiles type declarations without any problems, and is a part of build/test script.

I'll pick it up sometime during the week, hopefully will find a nice solution.

**Comment by qwelias** [comment]
Current _type coverage_ is not perfect -- still a lot of `any`, but should be enough for basic usage.
With this if someone would want to improve types on some part of the project they could just JSDoc it or write a TS type declaration and it should pop up in compiled declarations

**Comment by WebReflection** [comment]
Thanks @qwelias , this still looks great! Just please squash it as single commit, so I can review all at once, thanks!

**Comment by qwelias** [comment]
@WebReflection squashed 👍

**Comment by WebReflection** [comment]
@qwelias released 🎆

thank you again for the help 👍

**Pull request merged**
