### PR TITLE
Add `meta` attributes

### PR DESCRIPTION
**Pull request by jarusll**
Added the following [meta](https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-media) attributes
- name - The metadata key
- content - The metadata value
- http-equiv - Special flags for the page
- charset - The character encoding
- media - Preffered stylesheet according to media queries

### CODE REVIEW

**Comment by WebReflection** [comment]
It's up and running 🥳

**Comment by jarusll** [comment]
Am I  supposed to push `worker.js` as well? 
Also you might want to delete the github action `[node.build.js.yml](https://github.com/WebReflection/linkedom/blob/main/.github/workflows/node.build.js.yml)`, I pushed it without realizing there was already one present.

**Comment by jarusll** [comment]
If [node.build.js.yml](https://github.com/WebReflection/linkedom/blob/main/.github/workflows/node.build.js.yml) is not deleted by the next PR, I will include it in the PR. Thanks and please let me know if I am supposed to push `worker.js` or not.

**Comment by WebReflection** [comment]
worker comes out of hte build which happens anyway before I push versions from main ... in theory all PRs need is to change the *./esm/* and the *./test/* entry and everything else is handled by the pipe ... I will remove that .yml file then.

**Comment by WebReflection** [comment]
.yml removed ... maybe I could take a chance to update mine with more versions and a v3 checkout ... right now that's not a priority neither necessary, I hope that's OK.

**Pull request merged**
